// Package stations serves the baked station index behind GET /api/v1/stops.
// The list is generated by tools/build-stations.js from the TfNSW GTFS
// bundles; the server makes no upstream call to search it.
package stations

import (
	_ "embed"
	"encoding/json"
	"regexp"
	"sort"
	"strings"
)

//go:embed stations.json
var indexJSON []byte

// Location is a station's WGS84 position.
type Location struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

// Stop is one station, in the shape docs/contracts/api.md publishes.
type Stop struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Modes    []string  `json:"modes"`
	Location *Location `json:"location"`
}

var index = func() []Stop {
	var stops []Stop
	if err := json.Unmarshal(indexJSON, &stops); err != nil {
		panic("stations: embedded index is not valid JSON: " + err.Error())
	}
	return stops
}()

// All returns the whole index, in id order.
func All() []Stop { return index }

// Search ranks the index against an already-normalised query and returns at
// most limit matches, best first. Scoring mirrors web/js/search.js so the two
// clients rank the same list the same way.
func Search(query string, limit int) []Stop {
	type scored struct {
		stop  Stop
		order int
		score int
	}
	// The scorer strips "station" from the name, so a query carrying the word
	// would otherwise never match the station it names.
	query = stationWord.ReplaceAllString(query, "")

	var matches []scored
	for i, stop := range index {
		if score := fuzzyScore(stop.Name, query); score > 0 {
			matches = append(matches, scored{stop: stop, order: i, score: score})
		}
	}
	sort.SliceStable(matches, func(i, j int) bool { return matches[i].score > matches[j].score })

	stops := make([]Stop, 0, len(matches))
	for _, m := range matches {
		if limit > 0 && len(stops) >= limit {
			break
		}
		stops = append(stops, m.stop)
	}
	return stops
}

var stationWord = regexp.MustCompile(`(?i)\bstation\b`)

func normalise(s string) string {
	return strings.ToLower(strings.Join(strings.Fields(s), " "))
}

// fuzzyScore is the port of web/js/search.js fuzzyScore. Any change here is a
// change there.
func fuzzyScore(name, query string) int {
	n := normalise(stationWord.ReplaceAllString(name, ""))
	q := normalise(query)
	switch {
	case q == "":
		return 0
	case n == q:
		return 1000
	case strings.HasPrefix(n, q):
		return 900 - (len(n) - len(q))
	}
	for i, word := range strings.Fields(n) {
		if strings.HasPrefix(word, q) {
			return 800 - i*10
		}
	}
	if at := strings.Index(n, q); at >= 0 {
		return 700 - at
	}
	distance := editDistance(n, q)
	if distance <= max(2, len(q)/3) {
		return 500 - distance*25
	}
	return 0
}

func editDistance(a, b string) int {
	prev := make([]int, len(b)+1)
	for i := range prev {
		prev[i] = i
	}
	for i := 1; i <= len(a); i++ {
		diagonal := prev[0]
		prev[0] = i
		for j := 1; j <= len(b); j++ {
			above := prev[j]
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			prev[j] = min(prev[j]+1, min(prev[j-1]+1, diagonal+cost))
			diagonal = above
		}
	}
	return prev[len(b)]
}
